#! /usr/bin/env bash
#########################################################################
#									#
# Author: Copyright (C) 2018, 2024  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0					#
#									#
# Purpose:								#
# A Debian package post installation script for the dnsmasq-logrotate	#
# package. The script invokes the dnsmasq-postrotate script. See the	#
# man page for this script for further information.			#
#									#
# Exit Codes:	0 - success						#
#		1 - failure						#
#									#
#########################################################################


# Bail out on error.
set -e

##################
# Init variables #
##################
version="1.0.4"				# set version variable

########
# Main #
########

dnsmasq-postrotate

#DEBHELPER#

exit 0

